version: "3.9"
services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data  # Montar la carpeta de datos para persistencia
    environment:
      - SQLITE_NAME=movies.sqlite
      - SQLITE_DIR=/app/data
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000
